
load("//tensorflow:tensorflow.bzl", "tf_copts")

cc_library(
   name = "antlr_lib",
   srcs = ["libantlr4-runtime.a"],
   visibility = ["//visibility:public"],
   linkstatic = 1,
   alwayslink = 1,
)