
load("//tensorflow:tensorflow.bzl", "tf_copts")

cc_library(
    name = "concurrent_queue",
    srcs = glob(["*.h"]),
    hdrs = glob(["*.h"]),
    linkstatic = 1,
    visibility = ["//visibility:public"],
    deps = [
            "//tensorflow/core:framework_headers_lib",
            ],
    alwayslink=1,
)
