
load(
    "//tensorflow/core:platform/default/build_config.bzl",
    "tf_proto_library",
    "tf_proto_library_cc",
)

tf_proto_library_cc(
    name = "alignment_proto",
    srcs = ["alignment.proto"],
    cc_api_version = 2,
    visibility = ["//visibility:public"],
)
